In [3]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)


tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2,5])

In [7]:
y

tensor([[0.2459, 0.3503, 0.8895, 0.2739, 0.7451],
        [0.7128, 0.5004, 0.1848, 0.6757, 0.0682]])

In [9]:
y.view([1,10])
#similar to reshape in numpy

tensor([[0.2459, 0.3503, 0.8895, 0.2739, 0.7451, 0.7128, 0.5004, 0.1848, 0.6757,
         0.0682]])