In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[1.1,2,3],[6,5,7]])

In [6]:
type(b[1][0])
#all data converted into float type

numpy.float64

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
#get shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [12]:
#get type
a.dtype

dtype('int64')

In [13]:
#get size
a.itemsize

8

In [16]:
a.size*a.itemsize

24

In [17]:
a.nbytes

24

In [18]:
b.itemsize

8

In [19]:
b.nbytes

48

In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a[1,5]
#a[1][5] , alternate way

13

In [26]:
#get a specific row
a[0,:]
#a[0] also works

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
a[0,1:6:2]
#jump by 2

array([2, 4, 6])

In [33]:
#3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [34]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
#get a specific element
b[0,1,:]

array([3, 4])

In [41]:
#all zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
#all ones matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [44]:
#full with shape
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
#full like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
#generate random matrix
np.random.rand(4,2)

array([[0.5882964 , 0.20051647],
       [0.54817941, 0.59950105],
       [0.76931092, 0.41966301],
       [0.9882865 , 0.56677594]])

In [48]:
np.random.random_sample(a.shape)

array([[0.8666271 , 0.10221224, 0.94976253, 0.23338568, 0.12576187,
        0.17791252, 0.02906287],
       [0.59451178, 0.55162241, 0.84907165, 0.97962126, 0.69224213,
        0.77778478, 0.46880366]])

In [54]:
#random integer values
np.random.randint(3,10,size=(3,3))

array([[6, 7, 3],
       [7, 8, 8],
       [8, 7, 4]])

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
#repeat an array vertically or horizontally , horiz - axis 1 and vice versa
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)

In [68]:
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
output = np.ones((5,5))

In [71]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
z[1,1]=9

In [76]:
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [77]:
output[1:4,1:4] = z

In [78]:
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [79]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [84]:
#maths
a = np.array([1,2,3,4])
print(a)
a = a+2
print(a)
a = a*2
print(a)

[1 2 3 4]
[3 4 5 6]
[ 6  8 10 12]


In [86]:
b = np.array([1,0,1,0])

In [87]:
a+b


array([ 7,  8, 11, 12])

In [88]:
np.sin(a)

array([-0.2794155 ,  0.98935825, -0.54402111, -0.53657292])

In [89]:
np.tan(a)

array([-0.29100619, -6.79971146,  0.64836083, -0.63585993])

In [90]:
#linear algerbra
a = np.full((2,3),1)

In [91]:
print(a
     )

[[1 1 1]
 [1 1 1]]


In [92]:
b = np.full((3,2),2)

In [93]:
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [94]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [95]:
c = np.identity(3)

In [97]:
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
np.linalg.det(c)

1.0

In [101]:
stats = np.array([[1,2,3],[4,5,6]])

In [102]:
print(stats)

[[1 2 3]
 [4 5 6]]


In [103]:
np.min(stats)

1

In [106]:
np.max(stats,axis=1)

array([3, 6])

In [107]:
np.max(stats,axis=0)

array([4, 5, 6])

In [110]:
np.sum(stats,axis=1)

array([ 6, 15])

In [111]:
#reorganizing arrays
before = np.array([[1,2,3,4],[5,6,7,8]])

In [112]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [113]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [117]:
after = before.reshape((8,1))

In [118]:
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [120]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [128]:
#horizontal stack
h1 = np.ones((2,4))
print(h1)
h2 = np.zeros((2,2))
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [129]:
#miscellaneous
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])